#!/usr/bin/env python3

# TODO:
#
# - restore background file retrieval (xrootd broken)
# - disable stanadlone background merging (YAML instead)
# - implement the -o option (currently rec_$GENERATOR.hipo) 
# - implement --seed for GEMC (currently generators only)
#

_logger = None

import os
import sys
import logging

class ColoredFormatter(logging.Formatter):
    def __init__(self, msg):
        self.length = 20
        self.colors = {'INFO':32,'WARNING':35,'CRITICAL':31,'ERROR':31}
        self.reset_seq = '\033[0m'
        self.color_seq = '\033[1;%dm'
        logging.Formatter.__init__(self, msg)
    def format(self, record):
        if record.levelname in self.colors:
            l = record.levelname
            record.levelname = '%-20s'%( (self.color_seq % self.colors[l]) + l + self.reset_seq)
            record.msg =  self.color_seq % (self.colors[l]) + record.msg + self.reset_seq
        else:
            l = self.length - len(self.reset_seq) - len(self.color_seq)
            record.levelname = ('%%-%ds'%l) % record.levelname
        return logging.Formatter.format(self, record)

class ColoredLogger(logging.Logger):
    def __init__(self, name):
        logging.Logger.__init__(self, name, logging.INFO)
        console = ExitingStreamHandler()
        console.setFormatter(ColoredFormatter('[%(levelname)s] %(message)s'))
        self.addHandler(console)
        return

class ExitingStreamHandler(logging.StreamHandler):
    def emit(self, record):
        self.setFormatter(ColoredFormatter('[%(levelname)s] %(message)s'))
        super().emit(record)
        if record.levelno >= logging.CRITICAL:
            sys.exit(record.levelno)

def run(cfg, cmd):
    _logger.info(' '.join(cmd))
    import subprocess
    p = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,universal_newlines=True,encoding='latin-1')
    hush = False
    for line in iter(p.stdout.readline, ''):
        if len(line.strip())>0:
            if cfg.quiet:
                if line.find('*********************************************************************') >= 0:
                    continue
                if line.find('-------- WWWW ------- G4Exception-START -------- WWWW -------') >= 0:
                    hush = True
                    continue
                elif line.find('-------- WWWW -------- G4Exception-END --------- WWWW -------') >= 0:
                    hush = False
                    continue
            if not hush:
                print(line.rstrip())
    p.wait()
    return p.returncode

# choose output filename based on input filename and new prefix/suffix:
def get_out(inp, prefix=None, suffix=None):
    o = os.path.basename(inp)
    if suffix:
        if o.rfind('.') > 0:
            o = o[:o.rfind('.')]
        o = o + suffix
    if prefix:
        o = prefix + o
    if os.path.exists(o):
        _logger.critical(f'output file {o} already exists, for input {inp}')
    return o

# run a clas12-mcgen event genetator:
def generate(cfg):
    o = cfg.gen[0]+'.dat'
    cmd = [cfg.gen[0]]
    cmd.extend(['--docker','--trig',str(cfg.n),'--seed',str(cfg.seed)])
    cmd.extend(cfg.gen[1:])
    return run(cfg,cmd), o

# run GEMC, with LUND input or internal generator:
def gemc(cfg, lund=None):
    cmd = ['gemc',cfg.gcard,f'-RUNNO={cfg.run}','-USE_GUI=0',f'-N={cfg.n}']
    if cfg.match:
        cmd.extend(['-SAVE_ALL_MOTHERS=1','-SKIPREJECTEDHITS=1','-INTEGRATEDRAW="*"','-NGENP=50'])
    if lund:
        o = get_out(lund, suffix='.hipo')
        cmd.append(f'-INPUT_GEN_FILE=LUND,{lund}')
    else:
        o = 'gemc.hipo'
        cmd.extend(cfg.gen[1:])
    cmd.append(f'-OUTPUT=hipo,{o}')
    return run(cfg,cmd), o

# run background merging:
def merge_background(cfg, inp):
    o = get_out(inp, prefix='bg_')
    cmd=['bg-merger','-i',inp,'-o',o]
    cmd.extend(cfg.back)
    return run(cfg,cmd), o

# run denoising:
def denoise(cfg, inp):
    o = get_out(inp, prefix='dn_')
    cmd=['denoise2.exe','-o',o,inp]
    return run(cfg,cmd), o

# run reconstruction:
def recon(cfg, inp):
    o = get_out(inp, prefix='rec_')
    cmd=['recon-util','-y',cfg.yaml,'-i',inp,'-o',o]
    return run(cfg,cmd), o

# run dst maker:
def dst(cfg, inp):
    o = get_out(inp, prefix='dst_')
    cmd=['dst-maker','-o',o,inp]
    return run(cfg,cmd), o

# retrieve background file via xrootd:
def get_background_file(b):
    uri = 'xroot://sci-xrootd.jlab.org'
    d = '/osgpool/hallb/clas12/backgroundfiles'
    if not b.startswith('/') or not run(['xrdfs',uri,'ls',b]):
        b = f'{d}/{b}'
        if 0 != run(['xrdfs',uri,'ls',b]):
            _logger.critical('failed to find background file:  '+b)
    if 0 != run(['xrdcp',f'{uri}/{b}','.']):
        _logger.critical('failed to retrieve background file:  '+b)
    return os.path.basename(b)

# runs a LUND file through entire simulation pipeline:
def lund_pipeline(cfg, lund):
    if cfg.jobs > 1:
        make_workdir('.')
    ret,o = gemc(cfg, lund)
    if ret != 0:
        _logger.error('gemc failed.')
        return ret,o
    if len(cfg.back) > 0:
        ret,o = merge_background(cfg, o)
        if ret != 0:
            _logger.error('background merging failed.')
            return ret,o
    if cfg.denoise:
        ret,o = denoise(cfg, o)
        if ret != 0:
            _logger.error('denoising failed.')
            return ret,o
    ret,o = recon(cfg, o)
    if ret != 0:
        _logger.error('reconstruction failed.')
        return ret,o
    if cfg.dst:
        ret,o = dst(cfg, o)
        if ret != 0:
            _logger.error('dst making failed.')
            return ret,o
    return ret,o

# run a generator through entire simulation pipeline:
def generator_pipeline(cfg):
    if cfg.jobs > 1:
        make_workdir('.')
    ret,o = generate(cfg)
    if ret != 0:
        _logger.error(f'generator {cfg.gen[0]} failed.')
        return ret,o
    return lund_pipeline(cfg, o)

# launch parallel pipelines and wait for them to fininsh:
def launch_pipelines(cfg):
    status = []
    import concurrent.futures as cf
    with cf.ThreadPoolExecutor(max_workers=cfg.jobs) as exe:
        futures = []
        if cfg.gen[0] == 'lund':
            for j in range(cfg.jobs):
                if j > len(cfg.gen):
                    _logger.warning(f'insufficient LUND files for {cfg.jobs} jobs.')
                    break
                lund = cfg.gen[1+j]
                futures.append(exe.submit(lund_pipeline,cfg,lund))
        else:
            for j in range(cfg.jobs):
                futures.append(exe.submit(generator_pipeline,cfg))
        for f in futures:
            cf.wait([f])
            if f.exception() is not None:
                print(f.exception())
                status.append(1)
                continue
            ret,o = f.result()
            status.append(ret)
    return sum(status)

# make and change to a new working directory: 
def make_workdir(d):
    import tempfile
    import datetime
    if not os.path.isdir(d):
        if os.path.isfile(d): _logger.critical(f'invalid --tmpdir {cfg.tmpdir} is a file')
        try: os.makedirs(d)
        except AttributeError as e: _logger.critical(f'error creating directory --tmpdir {cfg.tmpdir}')
    date =datetime.datetime.now().strftime('%Y%m%d-%H:%M:%S')
    try: d = tempfile.mkdtemp(dir=d,prefix=f'mcdj-{date}-')
    except OSError as e: _logger.critical('error creating new directory in --tmpdir {cfg.tmpdir}')
    _logger.warning(f'using new working directory:  {d} ...')
    return d

def configure(args):

    # parse command-line:
    import argparse
    cli = argparse.ArgumentParser(description='CLAS12 Monte-Carlo Deejay',
            epilog='All executables must be in $PATH.  Generator command-line options can '
            'be placed after a "--", e.g., if sharing the same name as one of mcdj\'s.  '
            'See https://github.com/jeffersonlab/clas12-config for configuration files.')
    #cli.add_argument('-o',help='output HIPO file',metavar='PATH')
    cli.add_argument('-n',default=10,type=int,help='number of events (default=10)',metavar='#')
    cli.add_argument('-j','--jobs',default=1,type=int,help='number of parallel jobs (default=1)',metavar='#')
    cli.add_argument('-g','--gcard',required=True,type=str,help='GEMC gcard configuration file',metavar='PATH')
    cli.add_argument('-y','--yaml',required=True,type=str,help='COATJAVA yaml configuration file',metavar='PATH')
    cli.add_argument('-r','--run',default=11,type=int,help='run number (default=11)')
    cli.add_argument('-m','--match',default=False,action='store_true',help='enable truth matching')
    cli.add_argument('-b','--back',default=[],action='append',help='background files for merging',metavar='PATH')
    cli.add_argument('-s','--seed',default=0,type=int,help='random number seed (default=clock)')
    cli.add_argument('-d','--dst',default=False,action='store_true',help='run standalone dst-maker')
    cli.add_argument('-q','--quiet',default=False,action='store_true',help='silence GEANT4 exceptions')
    cli.add_argument('-v','--verbose',default=0,action='count',help='increase verbosity (repeatable)')
    cli.add_argument('--denoise',default=False,action='store_true',help='enable *old* denoising (use YAML for new)')
    cli.add_argument('gen',nargs='+',help='generator command line, or LUND file')
    cfg = cli.parse_args(args)

    if len(cfg.back) > 0:
        cli.warning('ignoring broken --back option')
        cfg.back = []

    # configure logger:
    global _logger
    logging.setLoggerClass(ColoredLogger)
    _logger = logging.getLogger(__name__)
    _logger.setLevel(20-10*cfg.verbose)

    # check existence of executables in $PATH:
    import shutil
    executables = ['gemc','bg-merger','denoise2.exe','recon-util','dst-maker']
    for exe in filter(lambda x: not shutil.which(x), executables):
        _logger.critical('executable not found in $PATH: '+exe)

    # determine event generator:
    if cfg.gen[0] == 'gemc':
        _logger.warning('using GEMC internal generator.')
        _logger.warning('using generator options:  '+' '.join(cfg.gen[1:]))
    elif shutil.which(cfg.gen[0]):
        _logger.warning('using generator found in $PATH:  '+shutil.which(cfg.gen[0]))
        _logger.warning('using generator options:  '+' '.join(cfg.gen[1:]))
    else:
        _logger.warning('generator not found in $PATH, interpreting as LUND file(s) ...')
        for f in filter(lambda x: not os.path.isfile(x),cfg.gen[1:]):
            _logger.critical(f'LUND file does not exist:  {f}.')
        cfg.gen.insert(0, 'lund')

    # convert to absolute paths:
    if os.path.isfile(cfg.gcard):
        cfg.gcard = os.path.abspath(cfg.gcard)
    if os.path.isfile(cfg.yaml):
        cfg.yaml = os.path.abspath(cfg.yaml)

    # check existence of configuration files:
    if not os.path.isfile(cfg.gcard):
        _logger.critical(f'invalid gcard: {cfg.gcard}')
    if not os.path.isfile(cfg.yaml):
        _logger.critical(f'invalid yaml: {cfg.yaml}')

    # retrieve background files:
    for i,b in enumerate(cfg.back):
        if not os.path.isfile(b):
            cfg.back[i] = get_background_file(b)

    _logger.debug('config:  '+str(cfg))

    return cfg

if __name__ == '__main__':

    sys.exit(launch_pipelines(configure(sys.argv[1:])))

