#!/bin/sh

# if ($1==NULL) return;

source /group/clas12/packages/setup.sh 
module load coatjava/6b.4.1

# export JAVA_HOME=/apps/scicomp/java/x64/jdk1.8;
# export PATH=$JAVA_HOME/bin:$PATH;
# export clara_version=4.3.5;
# export coatjava_version=5b.7.8;
# export WORK=/work/clas12/rg-b/clas12_clara$clara_version\_coatjava$coatjava_version;
# export CLARA_HOME=$WORK/clara;
# export COATJAVA=$CLARA_HOME/plugins/clas12;
# export PATH=$COATJAVA/bin:$PATH;

MALLOC_ARENA_MAX=1; 
export MALLOC_ARENA_MAX

# export dir=/work/clas12/rg-b/production/recon/pass0/v17/recon
# export dir=/work/clas12/rg-b/production/recon/pass0/v17/train
export dir=/work/clas12/rg-b/production/recon/pass0/v17/mon/recon
# echo $dir


#for xx in `ls $1 | grep 00001`  
#do echo $xx;

# for xx in `ls $1s2` ; do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_pid11 $1s2/$xx ./$1_skim-e/skim-e_$xx; done

# for xx in `ls $1s2` ; do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_trackPairs $1s2/$xx ./$1_skim-mu/skim-mu_$xx; done

# for xx in `ls $1 | grep "evio.00[3-6]"` ; do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_FT $1/$xx ./$1_skim-FT/skim-FT_$xx; done

# for xx in `ls $1 | grep "evio.006"` ; do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_FT $1/$xx ./$1_skim-FT/skim-FT_$xx; done

# for xx in `ls $dir/$1 | grep "0001[5-6].hipo"`
# do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_pid11 $dir/$1/$xx $dir/$1_skim-e_newnew/skim-e_$xx

mkdir $dir/$1_skim-e
# for xx in `ls $dir/$1 |grep "evio.0000"` 
# for xx in `ls $dir/$1 | grep "mon" |grep "evio.01"` 
for xx in `ls $dir/$1`
do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_pid11 $dir/$1/$xx $dir/$1_skim-e/skim-e_$xx

# mkdir $dir/$1_skim-trackpairs
# for xx in `ls $dir/$1` 
# do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_trackPairs $dir/$1/$xx $dir/$1_skim-trackpairs/skim-trackpairs_$xx

# for xx in `ls ./ |grep 0` 
# do hipo-utils -filter -b "RF::tdc,RF::adc,RUN::rf,REC::Particle,REC::Scintillator,RUN::config" -e "RUN::config" -merge -o calib_rf_$xx.hipo $xx/skim4*


# `ls -lth 011050_skim-e/* | grep 101K | awk '{print $9}'`


# for xx in {497..497}
# do echo $xx;
# do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_trackPairs $1/mon_clas_$1.evio.00$xx.hipo ./$1_skim-mu/skim-mu_mon_clas_$1.evio.00$xx.hipo;
# done

# for xx in `ls mon_clas_006213.evio.00000.hipo`  
# # do echo $xx;
# do java -DCLAS12DIR="$COATJAVA" -cp "$COATJAVA/lib/clas/*:$COATJAVA/lib/utils/*:." filter_pid11 $xx skim-e_$xx;
# done

done