name: Validation-latest

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: Bpolitycki/setup-xmllint-action@1.0.1
      - name: json
        run: find . -name '*.json' -exec python3 -c 'import json ; print(json.load(open("{}")))' \;
      - name: yaml
        run: find . -name '*.yaml' -exec python3 -c 'import yaml ; print(yaml.unsafe_load("\n".join(open("{}").readlines())))' \;
      - name: xml
        run: find . -name '*.xml' -exec xmllint {} \;
