name: Linting

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: Bpolitycki/setup-xmllint-action@1.0.1
      - name: json
        run: find . -name '*.json' -printf 'import json ; print(json.load(open("%p")))\n' | xargs -0 python3 -c
      - name: yaml
        run: find . -name '*.yaml' -printf 'import yaml ; print(yaml.unsafe_load("\n".join(open("%p").readlines())))' | xargs -0 python3 -c
      - name: xml
        run: find . -name '*.gcard' | xargs xmllint
