name: Validation-dev

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@main
    with:
      config_file_versions: >-
        {
          "coatjava": "latest",
          "gemc":     "dev"
        }
      git_upstream: >-
        {
          "clas12Tags": { "fork": "gemc/clas12Tags", "ref": "dev" }
        }
