name: Validation-dev

on:
  pull_request:
    branches: [ dev ] # PRs which target `dev`
    paths-ignore:
      - 'wok/**'
  push:
    branches: [ dev ] # pushes on `dev` (and merging PRs to `dev`)
    paths-ignore:
      - 'wok/**'
  workflow_dispatch: # manual trigger

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@main
    with:
      gemc_version: build
      config_file_versions: >-
        {
          "coatjava": "latest",
          "gemc":     "dev"
        }
      git_upstream: >-
        {
          "clas12Tags": { "fork": "gemc/clas12Tags", "ref": "dev" }
        }
